name: Build debian package

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Make debian package
      run: |
          cd debian && \
          docker build -t openwec-builder:debian -f Dockerfile . && \
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/../:/SRC  \
            --env CARGO_HOME=/SRC/target/.cargo openwec-builder:debian \
            cargo deb --manifest-path=../server/Cargo.toml
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: openwec-deb-package
        path: ./target/debian/*.deb
