name: Build debian bookworm package

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make debian package
      run: |
          cd build-pkg && \
          docker build -t openwec-builder:debian-bookworm -f Dockerfile-debian-bookworm . && \
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/../:/SRC  \
            --env CARGO_HOME=/SRC/target/.cargo openwec-builder:debian-bookworm \
            cargo deb --manifest-path=./server/Cargo.toml
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: openwec-deb-bookworm-package
        path: ./target/build-pkg/*.deb
