name: Generate Github release draft

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make debian bookworm package
      run: |
          cd build-pkg && \
          docker build -t openwec-builder:debian-bookworm -f Dockerfile-debian-bookworm . && \
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/../:/SRC  \
            --env CARGO_HOME=/SRC/target/.cargo openwec-builder:debian-bookworm \
            cargo deb --manifest-path=./server/Cargo.toml
    - name: Upload debian bookworm package
      uses: actions/upload-artifact@v3
      with:
        name: openwec-deb-bookworm-package
        path: ./target/debian/*.deb
    - name: Make debian bullseye package
      run: |
          cd build-pkg && \
          docker build -t openwec-builder:debian-bullseye -f Dockerfile-debian-bullseye . && \
          docker run -t -u $(id -u):$(id -g) -v $(pwd)/../:/SRC  \
            --env CARGO_HOME=/SRC/target/.cargo openwec-builder:debian-bullseye \
            cargo deb --manifest-path=./server/Cargo.toml
    - name: Upload debian bullseye package
      uses: actions/upload-artifact@v3
      with:
        name: openwec-deb-bullseye-package
        path: ./target/debian/*.deb
  release:
    name: Github release draft
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download debian bookworm package
        uses: actions/download-artifact@v3
        with:
          name: openwec-deb-bookworm-package
          path: debian-bookworm/
      - name: Download debian bullseye package
        uses: actions/download-artifact@v3
        with:
          name: openwec-deb-bullseye-package
          path: debian-bullseye/
      - name: Get artifacts names
        id: artifacts_names
        run: |
          echo "U_PKG_DEB_BOOKWORM=$(ls debian-bookworm/openwec*.deb)" >> "$GITHUB_OUTPUT" && \
          echo "U_PKG_DEB_BULLSEYE=$(ls debian-bullseye/openwec*.deb)" >> "$GITHUB_OUTPUT"
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ steps.artifacts_names.outputs.U_PKG_DEB_BOOKWORM }}
            ${{ steps.artifacts_names.outputs.U_PKG_DEB_BULLSEYE }}
